CREATE DATABASE ERP;

CREATE TABLE ERP.ORDEMVENDA (
	ID           	INT        NOT NULL AUTO_INCREMENT,
	PRODUTO      	VARCHAR(255)  NOT NULL,
	QUANTIDADE	INT NOT NULL,
	CONSTRAINT PK_ORDEMVENDA PRIMARY KEY (ID)
);

CREATE TABLE ERP.MATERIAPRIMA (
	ID   			INT          NOT NULL AUTO_INCREMENT,
	NOME			VARCHAR(255) NOT NULL,
	QUANTIDADE	INT	NOT NULL,
	FABRICANTE	VARCHAR(100),
	SELECIONADO	BOOLEAN,
	CONSTRAINT PK_MATERIAPRIMA PRIMARY KEY (ID)
);

CREATE TABLE ERP.ORDEMPRODUCAO (
    ID   				INT NOT NULL,
    QUANTIDADERECURSO	INT NOT NULL,
    STATU				VARCHAR(255),
    DATAINICIO			VARCHAR(10),
    DATATERMINO			VARCHAR(10),
    DATAPREV			VARCHAR(10),
    TEMPOESTIMADO		VARCHAR(255),
	RECURSOS			INT NOT NULL,
    ID_ORDEMVENDA		INT NOT NULL,
    
    CONSTRAINT PK_ORDEMPRODUCAO PRIMARY KEY (ID),
    CONSTRAINT FK_ORDEMVENDA FOREIGN KEY (ID_ORDEMVENDA) REFERENCES ERP.ORDEMVENDA(ID)
);

CREATE TABLE ERP.ORDEMPRODUCAO_MATERIAPRIMA (
    ID_ORDEMPRODUCAO	INT NOT NULL,
    ID_MATERIAPRIMA 	INT	NOT NULL,
    CONSTRAINT FK_ORDEMPRODUCAO	FOREIGN KEY (ID_ORDEMPRODUCAO)	REFERENCES ERP.ORDEMPRODUCAO(ID),
    CONSTRAINT FK_MATERIAPRIMA 	FOREIGN KEY (ID_MATERIAPRIMA) 	REFERENCES ERP.MATERIAPRIMA(ID)
);

INSERT INTO ERP.ORDEMVENDA (PRODUTO, QUANTIDADE) VALUES ('REFRIGUERANTE', 2);
INSERT INTO ERP.ORDEMVENDA (PRODUTO, QUANTIDADE) VALUES ('Merda', 2);

INSERT INTO ERP.MATERIAPRIMA (nome, quantidade, fabricante) values ('Placa mãe', 65, 'Lenovo');
INSERT INTO ERP.MATERIAPRIMA (nome, quantidade, fabricante) values ('Memória RAM', 42, 'SanDisck');

SELECT ID, PRODUTO, QUANTIDADE FROM ERP.ORDEMVENDA WHERE ID =1;
