CREATE DATABASE ERP;

CREATE TABLE ERP.ORDEMVENDA (
	ID           	INT        NOT NULL AUTO_INCREMENT,
	PRODUTO      	VARCHAR(255)  NOT NULL,
	QUANTIDADE	INT NOT NULL,
	CONSTRAINT PK_ORDEMVENDA PRIMARY KEY (ID)
);

CREATE TABLE ERP.MATERIAPRIMA (
	ID   			INT          NOT NULL AUTO_INCREMENT,
	NOME			VARCHAR(255) NOT NULL,
	QUANTIDADE		INT	NOT NULL,
	FABRICANTE		VARCHAR(100),
	SELECIONADO		BOOLEAN,
    QUANTUTILIZADA	INT NOT NULL,
	CONSTRAINT PK_MATERIAPRIMA PRIMARY KEY (ID)
);

CREATE TABLE ERP.ORDEMPRODUCAO (
    ID   				INT NOT NULL,
    RECURSOS			INT NOT NULL,
    STATU				VARCHAR(255),
    DATAINICIO			VARCHAR(10),
    DATATERMINO			VARCHAR(10),
    DATAPREV			VARCHAR(10),
    TEMPOESTIMADO		VARCHAR(255),
    ID_ORDEMVENDA		INT NOT NULL,
    
    CONSTRAINT PK_ORDEMPRODUCAO PRIMARY KEY (ID),
    CONSTRAINT FK_ORDEMVENDA FOREIGN KEY (ID_ORDEMVENDA) REFERENCES ERP.ORDEMVENDA(ID)
);

CREATE TABLE ERP.ORDEMPRODUCAO_MATERIAPRIMA (
    ID_ORDEMPRODUCAO	INT NOT NULL,
    ID_MATERIAPRIMA 	INT	NOT NULL,
    PRIMARY KEY (ID_ORDEMPRODUCAO, ID_MATERIAPRIMA),
    CONSTRAINT FK_ORDEMPRODUCAO	FOREIGN KEY (ID_ORDEMPRODUCAO)	REFERENCES ERP.ORDEMPRODUCAO(ID),
    CONSTRAINT FK_MATERIAPRIMA 	FOREIGN KEY (ID_MATERIAPRIMA)	REFERENCES ERP.MATERIAPRIMA(ID)
);

INSERT INTO ERP.ORDEMVENDA (PRODUTO, QUANTIDADE) VALUES ('REFRIGUERANTE', 2);
INSERT INTO ERP.ORDEMVENDA (PRODUTO, QUANTIDADE) VALUES ('Merda', 2);

INSERT INTO ERP.MATERIAPRIMA (nome, quantidade, fabricante, selecionado, QUANTUTILIZADA) values ('Placa mãe', 65, 'Lenovo', true, 0);
INSERT INTO ERP.MATERIAPRIMA (nome, quantidade, fabricante, selecionado, QUANTUTILIZADA) values ('Memória RAM', 42, 'SanDisck', true, 0);

SELECT ID, PRODUTO, QUANTIDADE FROM ERP.ORDEMVENDA WHERE ID =1;

select * from ERP.ORDEMPRODUCAO_MATERIAPRIMA;

SELECT  OP.*, OV.PRODUTO, OV.QUANTIDADE FROM ERP.ORDEMPRODUCAO OP 
INNER JOIN ERP.ORDEMVENDA OV ON OP.ID_ORDEMVENDA = OV.ID;

SELECT OP.*, M.NOME, M.QUANTIDADE, M.FABRICANTE, M.SELECIONADO, M.QUANTUTILIZADA, OM.ID_MATERIAPRIMA FROM ERP.ORDEMPRODUCAO OP 
INNER JOIN ERP.ORDEMPRODUCAO_MATERIAPRIMA OM ON OP.ID = OM.ID_ORDEMPRODUCAO
INNER JOIN ERP.MATERIAPRIMA M ON M.ID = OM.ID_MATERIAPRIMA WHERE OP.ID = 3313;

SELECT  OP.*, OV.PRODUTO, OV.QUANTIDADE FROM ERP.ORDEMPRODUCAO OP
INNER JOIN ERP.ORDEMVENDA OV ON OP.ID_ORDEMVENDA = OV.ID WHERE OP.ID = 65;
