/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.erp.telas;

import br.com.senac.erp.daos.DaoMateriaPrima;
import br.com.senac.erp.daos.DaoOrdemProducao;
import br.com.senac.erp.daos.DaoOrdemVenda;
import br.com.senac.erp.model.MateriaPrima;
import br.com.senac.erp.model.OrdemProducao;
import br.com.senac.erp.model.OrdemVenda;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VictorGuilhermeSeraf
 */
public class TelaLista extends javax.swing.JFrame {

    /**
     * Creates new form TelaLista
     */
    public TelaLista() {
        initComponents();
        carregarTabelaOrdens();
    }

    DaoOrdemVenda daoVenda = new DaoOrdemVenda();
    DaoMateriaPrima daoMateria = new DaoMateriaPrima();
    DaoOrdemProducao daoProducao = new DaoOrdemProducao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        ListaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordemTable = new javax.swing.JTable();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        OrdemProducaoLabel = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JButton();
        producaoPanel = new javax.swing.JPanel();
        OrdemProducaoLabel1 = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        codigoVendaLabel = new javax.swing.JLabel();
        codigoVendaTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        produtoProdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        materiaTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnBuscarVenda = new javax.swing.JButton();
        quantidadeProdTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dataIniciotxt = new javax.swing.JFormattedTextField();
        dataPrevtxt = new javax.swing.JFormattedTextField();
        dataTermtxt = new javax.swing.JFormattedTextField();
        tempotxt = new javax.swing.JFormattedTextField();
        recursosTxt = new javax.swing.JFormattedTextField();
        btnAlteracao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        ordemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número da Ordem", "Produto", "Data de Ínicio", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ordemTable);

        btnInserir.setText("Nova Ordem");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar Ordem");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        OrdemProducaoLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        OrdemProducaoLabel.setText("Ordem de Produção");

        btnRelatorio.setText("Gerar Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaPanelLayout = new javax.swing.GroupLayout(ListaPanel);
        ListaPanel.setLayout(ListaPanelLayout);
        ListaPanelLayout.setHorizontalGroup(
            ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPanelLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ListaPanelLayout.createSequentialGroup()
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OrdemProducaoLabel)
                    .addComponent(jScrollPane1))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(ListaPanelLayout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListaPanelLayout.setVerticalGroup(
            ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrdemProducaoLabel)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(ListaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(btnRelatorio)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        mainPanel.add(ListaPanel, "listaPanel");

        OrdemProducaoLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        OrdemProducaoLabel1.setText("Ordem de Produção");

        codigoLabel.setText("Código:");

        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });

        codigoVendaLabel.setText("Código Venda:");

        codigoVendaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoVendaTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto a ser produzido:");

        jLabel2.setText("Quantidade:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Recursos para produção");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Matéria prima:");

        materiaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(false), null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Código Produto", "Nome Produto", "Quantidade", "Fabricante", "Quantidade a ser utilizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(materiaTable);
        if (materiaTable.getColumnModel().getColumnCount() > 0) {
            materiaTable.getColumnModel().getColumn(0).setMinWidth(22);
            materiaTable.getColumnModel().getColumn(0).setMaxWidth(22);
            materiaTable.getColumnModel().getColumn(1).setMinWidth(100);
            materiaTable.getColumnModel().getColumn(1).setMaxWidth(100);
            materiaTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel5.setText("Recursos operacionais (Quantidade):");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Informações Operacionais");

        jLabel7.setText("Status da produção:");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um status ...", "Em produção", "Pêndente", "Aguardando manutenção de ativo", "Aguardando recurso", "Finalizado", "Cancelado" }));
        statusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de início:");

        jLabel9.setText("Data Término Prevista:");

        jLabel10.setText("Tempo de duração estimado:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar Ordem");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnBuscarVenda.setText("Buscar Ordem de Venda");
        btnBuscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVendaActionPerformed(evt);
            }
        });

        quantidadeProdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeProdTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Data Término:");

        try {
            dataIniciotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataIniciotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataIniciotxt.setText("00/00/0000");

        try {
            dataPrevtxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataPrevtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataPrevtxt.setText("00/00/0000");

        try {
            dataTermtxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataTermtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataTermtxt.setText("00/00/0000");

        try {
            tempotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##h##min")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tempotxt.setText("00h00min");
        tempotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempotxtActionPerformed(evt);
            }
        });

        try {
            recursosTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        recursosTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recursosTxt.setText("  ");

        btnAlteracao.setText("Alterar");
        btnAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout producaoPanelLayout = new javax.swing.GroupLayout(producaoPanel);
        producaoPanel.setLayout(producaoPanelLayout);
        producaoPanelLayout.setHorizontalGroup(
            producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producaoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OrdemProducaoLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(producaoPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(producaoPanelLayout.createSequentialGroup()
                        .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, producaoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataIniciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataPrevtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(producaoPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(recursosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6)
                                .addGroup(producaoPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataTermtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(producaoPanelLayout.createSequentialGroup()
                        .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(producaoPanelLayout.createSequentialGroup()
                                .addComponent(btnAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, producaoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, producaoPanelLayout.createSequentialGroup()
                                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, producaoPanelLayout.createSequentialGroup()
                                        .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(producaoPanelLayout.createSequentialGroup()
                                                .addComponent(codigoVendaLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(codigoVendaTxt))
                                            .addGroup(producaoPanelLayout.createSequentialGroup()
                                                .addComponent(codigoLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(472, 472, 472)))
                        .addGap(276, 276, 276))
                    .addGroup(producaoPanelLayout.createSequentialGroup()
                        .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(producaoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(produtoProdTxt))
                            .addGroup(producaoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tempotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantidadeProdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(502, 502, 502))))
        );
        producaoPanelLayout.setVerticalGroup(
            producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producaoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(OrdemProducaoLabel1)
                .addGap(18, 18, 18)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoVendaLabel)
                    .addComponent(codigoVendaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVenda))
                .addGap(18, 18, 18)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(produtoProdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(quantidadeProdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recursosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataTermtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(dataIniciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataPrevtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tempotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(producaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar)
                    .addComponent(btnCancelar)
                    .addComponent(btnAlteracao))
                .addGap(45, 45, 45))
        );

        mainPanel.add(producaoPanel, "producaoPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "producaoPanel");

        Random random = new Random();
        int contador = random.nextInt(5000);

        codigoTxt.setText("0" + Integer.toString((contador)));
        codigoTxt.setEditable(false);
        codigoTxt.setEnabled(true);
        codigoVendaTxt.setEnabled(true);
        produtoProdTxt.setEnabled(true);
        produtoProdTxt.setEditable(false);
        quantidadeProdTxt.setEnabled(true);
        quantidadeProdTxt.setEditable(false);
        dataIniciotxt.setEnabled(true);
        dataPrevtxt.setEnabled(true);
        btnBuscarVenda.setEnabled(true);
        tempotxt.setEnabled(true);
        recursosTxt.setEnabled(true);
        materiaTable.setEnabled(true);
        btnAlteracao.setEnabled(false);
        btnSalvar.setEnabled(true);
        carregarTabelaMateriaPrima();

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "producaoPanel");
        
        btnSalvar.setEnabled(false);
        btnAlteracao.setEnabled(true);

        codigoTxt.setEnabled(false);
        codigoVendaTxt.setEnabled(false);
        produtoProdTxt.setEnabled(false);
        quantidadeProdTxt.setEnabled(false);
        dataIniciotxt.setEnabled(false);
        dataPrevtxt.setEnabled(false);
        btnBuscarVenda.setEnabled(false);
        tempotxt.setEnabled(false);
        recursosTxt.setEnabled(false);
        materiaTable.setEnabled(false);

        int row = ordemTable.getSelectedRow();
        int id = (int) ordemTable.getValueAt(row, 0);

        OrdemProducao ordemP = daoProducao.obter(id);

        List<MateriaPrima> materias = ordemP.getMaterias();

        System.out.println(materias);

        try {

            codigoTxt.setText(Integer.toString(ordemP.getId()));
            codigoVendaTxt.setText(Integer.toString(ordemP.getOrdemVenda().getId()));
            produtoProdTxt.setText(ordemP.getOrdemVenda().getProduto());
            quantidadeProdTxt.setText(Integer.toString(ordemP.getOrdemVenda().getQuantidadeProd()));

            DefaultTableModel model = (DefaultTableModel) materiaTable.getModel();
            model.setNumRows(0);

            for (MateriaPrima m : materias) {
                model.addRow(new Object[]{
                    m.isSelecionado(),
                    m.getId(),
                    m.getNome(),
                    m.getQuantidade(),
                    m.getFabricante()
                });
            }

            recursosTxt.setText("0" + Integer.toString(ordemP.getRecurso()));
            statusCombo.setSelectedItem(ordemP.getStatu());
            dataIniciotxt.setText(ordemP.getDataInicio());
            dataPrevtxt.setText(ordemP.getDataPrevista());
            dataTermtxt.setText(ordemP.getDataTermino());
            tempotxt.setText(ordemP.getTempoEstimado());
            
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "listaPanel");
        limpar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnBuscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVendaActionPerformed
        String idVenda = codigoVendaTxt.getText();

        if ("".equals(idVenda)) {
            JOptionPane.showMessageDialog(null, "Digite o número da Ordem de Venda!");
        } else {
            try {
                OrdemVenda ordemVenda = daoVenda.obter(Integer.parseInt(idVenda));
                produtoProdTxt.setText(ordemVenda.getProduto());
                quantidadeProdTxt.setText(Integer.toString(ordemVenda.getQuantidadeProd()));
            } catch (Exception e) {

            }

        }
    }//GEN-LAST:event_btnBuscarVendaActionPerformed

    private void quantidadeProdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeProdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeProdTxtActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void codigoVendaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoVendaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoVendaTxtActionPerformed

    private void tempotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempotxtActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        OrdemProducao ordemP = new OrdemProducao();
        OrdemVenda ordemV = new OrdemVenda();
        List<MateriaPrima> materias = new ArrayList<>();

        try {
            int rows = materiaTable.getRowCount();
            int cont = 0;
            for (int i = 0; i < rows; i++) {
                if ((boolean) materiaTable.getValueAt(i, 0)) {
                    cont++;
                }
            }
            if (cont > 0) {
                ordemV.setId(Integer.parseInt(codigoVendaTxt.getText()));
                ordemV.setProduto(produtoProdTxt.getText());
                ordemV.setQuantidadeProd(Integer.parseInt(quantidadeProdTxt.getText()));
                ordemP.setOrdemVenda(ordemV);

                ordemP.setId(Integer.parseInt(codigoTxt.getText()));
                ordemP.setRecurso(Integer.parseInt(recursosTxt.getText()));
                ordemP.setStatu((String) statusCombo.getSelectedItem());
                ordemP.setDataInicio(dataIniciotxt.getText());
                ordemP.setDataPrevista(dataPrevtxt.getText());
                ordemP.setDataTermino(dataTermtxt.getText());
                ordemP.setTempoEstimado(tempotxt.getText());

                for (int i = 0; i < rows; i++) {

                    MateriaPrima materia = new MateriaPrima();
                    if ((boolean) materiaTable.getValueAt(i, 0)) {
                        materia.setSelecionado((boolean) materiaTable.getValueAt(i, 0));
                        materia.setId((int) materiaTable.getValueAt(i, 1));
                        materia.setNome((String) materiaTable.getValueAt(i, 2));
                        int quantidade = (int) materiaTable.getValueAt(i, 3);
                        materia.setQuantidade(quantidade);
                        materia.setFabricante((String) materiaTable.getValueAt(i, 4));
                        int quantidadeUtilizada = (int) materiaTable.getValueAt(i, 3);
                        materia.setQuantidadeUtilizada(quantidadeUtilizada);
                        materias.add(materia);
                    }
                }
                ordemP.setMaterias(materias);
                daoProducao.inserir(ordemP);
                int resposta = JOptionPane.showConfirmDialog(null, "Deseja Salvar essa Ordem de produção?",
                        "Salvar", JOptionPane.OK_CANCEL_OPTION);
                if (resposta == 0) {
                    CardLayout card = (CardLayout) mainPanel.getLayout();
                    card.show(mainPanel, "listaPanel");
                    carregarTabelaOrdens();
                    limpar();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione os recursos que serão utilizado na produção!",
                        "Falta de Recursos", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaLista.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ordem de Produção não gerada!"
                    + "\nContate o desenvolvedor.", "Erro!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void statusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboActionPerformed

    }//GEN-LAST:event_statusComboActionPerformed

    private void btnAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlteracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListaPanel;
    private javax.swing.JLabel OrdemProducaoLabel;
    private javax.swing.JLabel OrdemProducaoLabel1;
    private javax.swing.JButton btnAlteracao;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarVenda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JLabel codigoVendaLabel;
    private javax.swing.JTextField codigoVendaTxt;
    private javax.swing.JFormattedTextField dataIniciotxt;
    private javax.swing.JFormattedTextField dataPrevtxt;
    private javax.swing.JFormattedTextField dataTermtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable materiaTable;
    private javax.swing.JTable ordemTable;
    private javax.swing.JPanel producaoPanel;
    private javax.swing.JTextField produtoProdTxt;
    private javax.swing.JTextField quantidadeProdTxt;
    private javax.swing.JFormattedTextField recursosTxt;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JFormattedTextField tempotxt;
    // End of variables declaration//GEN-END:variables

    private void carregarTabelaMateriaPrima() {

        DefaultTableModel model = (DefaultTableModel) materiaTable.getModel();
        model.setNumRows(0);
        try {
            boolean b = false;
            for (MateriaPrima m : daoMateria.listar()) {
                model.addRow(new Object[]{
                    m.isSelecionado(),
                    m.getId(),
                    m.getNome(),
                    m.getQuantidade(),
                    m.getFabricante(),
                    m.getQuantidadeUtilizada()
                });
            }
        } catch (Exception e) {
        }
    }

    private void carregarTabelaOrdens() {

        DefaultTableModel model = (DefaultTableModel) ordemTable.getModel();
        model.setNumRows(0);
        try {
            for (OrdemProducao p : daoProducao.listar()) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getOrdemVenda().getProduto(),
                    p.getDataInicio(),
                    p.getStatu(),});
            }
        } catch (Exception e) {
        }
    }
    
    private void limpar(){
        codigoTxt.setText("");
        codigoVendaTxt.setText("");
        produtoProdTxt.setText("");
        quantidadeProdTxt.setText("");
        recursosTxt.setText("");
        statusCombo.setSelectedIndex(0);
        dataIniciotxt.setText("00/00/0000");
        dataPrevtxt.setText("00/00/0000");
        dataTermtxt.setText("00/00/0000");
        tempotxt.setText("");
    }
}
